# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- pipeline


schedules:
- cron: "55 14 * * *"
  displayName: Daily 1000
  branches: 
    include:
    - pipeline
  always: true

- cron: "55 20 * * *"
  displayName: Daily 1600
  branches: 
    include:
    - pipeline
  always: true

- cron: "55 2 * * *"
  displayName: Daily 2200
  branches: 
    include:
    - pipeline
  always: true

pool:
  vmImage: ubuntu-latest 

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'
 
- script: |          
    npm install 
    npm install -g increase-memory-limit
    npm run build
    node app.js $(SERVER) $(USER) $(PW)